replicaCount: 1

image:
  repository: gcr.io/dummy
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 128Mi
