replicaCount: 1

image:
  repository: "dummy"
  tag: "dummy"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 128Mi

cloudsql:
  image: "dummy"
  command:
    - /cloud_sql_proxy
    - -instances=dummy
    - -credential_file=dummy
