cert-manager:
  install: true
  clusterResource: true
  email: keumartist.dev@gmail.com
  acmeServer: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretRef: letsencrypt-prod
  solvers:
    - http01:
        ingress:
          class: nginx
