grafana.ini:
  security:
    admin_user: admin
  auth:
    disable_login_form: false
    disable_signout_menu: true
  auth.anonymous:
    enabled: true
    org_role: Viewer

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

ingress:
  enabled: false

